services:
  - type: web
    name: tech-army-backend
    runtime: python
    region: singapore
    rootDir: Tech_Army
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn Tech_Army.wsgi:application
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOW_ALL
        value: "True"
