# Generated by Django 5.1b1 on 2024-08-12 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('personstatus', models.CharField(choices=[('Employee', 'Employee'), ('Lead', 'Lead'), ('Manager', 'Manager'), ('HR', 'HR')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManagerSheet',
            fields=[
                ('project_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dead_line', models.DateField()),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_sheets', to='tech_army_app.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='TeamleaderSheet',
            fields=[
                ('module_name', models.CharField(default='default_module', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_army_app.managersheet')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_army_app.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('comments', models.TextField()),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_army_app.managersheet')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_army_app.myuser')),
                ('module_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_army_app.teamleadersheet')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=20)),
                ('mon', models.IntegerField()),
                ('tue', models.IntegerField()),
                ('wed', models.IntegerField()),
                ('thu', models.IntegerField()),
                ('fri', models.IntegerField()),
                ('total', models.IntegerField()),
                ('leave_days', models.IntegerField(default=0)),
                ('lead_approval', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=20)),
                ('manager_approval', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_army_app.myuser')),
                ('module_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_army_app.teamleadersheet')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_army_app.managersheet')),
            ],
        ),
    ]
