# Generated by Django 5.0.7 on 2024-08-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_army_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='personstatus',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Lead', 'Lead'), ('Manager', 'Manager'), ('HR', 'HR'), ('Admin', 'Admin')], max_length=10),
        ),
    ]
