# Generated by Django 5.0.7 on 2024-08-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_army_app', '0002_alter_myuser_personstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='comments',
            field=models.CharField(default='comments', max_length=20),
            preserve_default=False,
        ),
    ]
